config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  resources :events 
  resources :users
  resources :event_attendances
  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :event_attendances, foreign_key: "attended_event_id", class_name: "EventAttendee"
  has_many :attendees, through: :event_attendances, source: :attendee

  scope :past, ->{where("event_date<?", Date.current)}
  scope :future, ->{where("event_date>=?", Date.current)}
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: "creator_id"
  has_many :event_attendances, foreign_key: "attendee_id", class_name: "EventAttendee"
  has_many :attended_events, through: :event_attendances, source: :attended_event

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_attendances_controller.rb
class EventAttendancesController < ApplicationController
  
  def new
      render
      @event_attendees = EventAttendee.new
      puts params
  end

  def create
    # puts params[:attended_event_id]
    puts params
    puts "hello"
    @attendee = current_user.event_attendances.build(attendee_params)

    if @attendee.save
      puts "your attendance is registered"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def attendee_params
      params.permit(:attended_event_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new,:create]

  def index
    @events = Event.all
    @events_future = @events.future
    @events_past = @events.past
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show 
    @event = Event.find(params[:id])
  end
  private
    def event_params
      params.require(:event).permit(:title, :description,:event_location,:event_date)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendances_helper.rb
module EventAttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<h1>All The Events </h1>

<h2>Upcoming Events </h2>
<ol>
  <% @events.future.each do |eve| %>
    <li>
      <h3>  <%= link_to eve.title, event_path(eve) %> </h3>
    </li>
<% end %>
</ol>


<h2>Past Events </h2>
<ol>
  <% @events.past.each do |eve| %>
    <li>
      <h3>  <%= link_to eve.title, event_path(eve) %> </h3>
    </li>
<% end %>
</ol>

app/views/events/new.html.erb
<h1>Create your event here</h1>

<%= form_with model: @event do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :event_location %><br>
    <%= form.text_field :event_location %>
  </div>

  <div>
    <%= form.label :event_date %><br>
    <%= form.datetime_field :event_date %>
  </div>

  <div>
    <%= form.submit :submit %>
  </div>
<% end %>

app/views/events/show.html.erb
<h1>  <%= @event.title %> </h1>
<p><strong> description: </strong><%= @event.description %> </p>
<p><strong> location:</strong> <%= @event.event_location %> </p>
<p><strong> date and time: </strong><%= @event.event_date %> </p>


<% if user_signed_in? %> 
<h3>Click on this button to register yourself for joining </h3>
<%= button_to 'Join Event', event_attendances_path, 
  params: { attended_event_id: @event.id }, method: :post %>
<% else %>
<h3>You need to first log in to join this event </h3>
<% end %>

<h1>  List of Attendees are as follow: </h1>
<ol>
  <% @event.attendees.each do |eve| %>
    <li>
      <h3>  <%= eve.email %> </h3>
    </li>
  <% end %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvent</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1> All the event that <%= @user.email %> has created are as follow </h1>
<ol>
  <% @user.events.each do |eve| %>
    <li>
      <h3>  <%= eve.title %> </h3>
       <p> description: <%= eve.description %> </p>
       <p> location: <%= eve.event_location %> </p>
       <p> date and time <%= eve.event_date %> </p>
    </li>
  <% end %>
</ol>


<h1>  List of Events this user attended: </h1>
<h2>Past Events</h2>
<ol>
  <% @user.attended_events.each do |event| %>
    <% if event.event_date < Date.current %>
      <li><%= event.title %></li>
    <% end %>
  <% end %>
</ol>

<h2>Future Events</h2>
<ol>
  <% @user.attended_events.each do |event| %>
    <% if event.event_date >= Date.current %>
      <li><%= event.title %></li>
    <% end %>
  <% end %>
</ol>